require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe API::V1::ProductCategoriesController, :type => :controller do
  let(:url) { "http://api.domain.com" }


  # This should return the minimal set of attributes required to create a valid
  # ProductCategory. As you add validations to ProductCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: "Water Drinks", status: "Active"}
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductCategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    pending "assigns all product_categories as @product_categories" do
      product_category = ProductCategory.create! valid_attributes
      get #{url}/product_categories", {}, valid_session
      expect(assigns(:product_categories)).to eq([product_category])
    end
  end

  describe "GET show" do
    pending "assigns the requested product_category as @product_category" do
      product_category = ProductCategory.create! valid_attributes
      get #{url}/product_categories", {:id => product_category.to_param}, valid_session
      expect(assigns(:product_category)).to eq(product_category)
    end
  end

  describe "GET new" do
    pending "assigns a new product_category as @product_category" do
      get #{url}/product_categories/new", {}, valid_session
      expect(assigns(:product_category)).to be_a_new(ProductCategory)
    end
  end

  describe "GET edit" do
    pending "assigns the requested product_category as @product_category" do
      product_category = ProductCategory.create! valid_attributes
      get #{url}/product_categories/edit", {:id => product_category.to_param}, valid_session
      expect(assigns(:product_category)).to eq(product_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      pending "creates a new ProductCategory" do
        expect {
          post #{url}/product_categories", {:product_category => valid_attributes}, valid_session
        }.to change(ProductCategory, :count).by(1)
      end

      pending "assigns a newly created product_category as @product_category" do
        post #{url}/product_categories", {:product_category => valid_attributes}, valid_session
        expect(assigns(:product_category)).to be_a(ProductCategory)
        expect(assigns(:product_category)).to be_persisted
      end

      pending "redirects to the created product_category" do
        post #{url}/product_categories", {:product_category => valid_attributes}, valid_session
        expect(response).to redirect_to(ProductCategory.last)
      end
    end

    describe "with invalid params" do
      pending "assigns a newly created but unsaved product_category as @product_category" do
        post #{url}/product_categories", {:product_category => invalid_attributes}, valid_session
        expect(assigns(:product_category)).to be_a_new(ProductCategory)
      end

      pending "re-renders the 'new' template" do
        post #{url}/product_categories", {:product_category => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      pending "updates the requested product_category" do
        product_category = ProductCategory.create! valid_attributes
        put #{url}/product_categories", {:id => product_category.to_param, :product_category => new_attributes}, valid_session
        product_category.reload
        skip("Add assertions for updated state")
      end

      pending "assigns the requested product_category as @product_category" do
        product_category = ProductCategory.create! valid_attributes
        put #{url}/product_categories", {:id => product_category.to_param, :product_category => valid_attributes}, valid_session
        expect(assigns(:product_category)).to eq(product_category)
      end

      pending "redirects to the product_category" do
        product_category = ProductCategory.create! valid_attributes
        put #{url}/product_categories", {:id => product_category.to_param, :product_category => valid_attributes}, valid_session
        expect(response).to redirect_to(product_category)
      end
    end

    describe "with invalid params" do
      pending "assigns the product_category as @product_category" do
        product_category = ProductCategory.create! valid_attributes
        put #{url}/product_categories", {:id => product_category.to_param, :product_category => invalid_attributes}, valid_session
        expect(assigns(:product_category)).to eq(product_category)
      end

      pending "re-renders the 'edit' template" do
        product_category = ProductCategory.create! valid_attributes
        put #{url}/product_categories", {:id => product_category.to_param, :product_category => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    pending "destroys the requested product_category" do
      product_category = ProductCategory.create! valid_attributes
      expect {
        delete #{url}/product_categories", {:id => product_category.to_param}, valid_session
      }.to change(ProductCategory, :count).by(-1)
    end

    pending "redirects to the product_categories list" do
      product_category = ProductCategory.create! valid_attributes
      delete #{url}/product_categories", {:id => product_category.to_param}, valid_session
      expect(response).to redirect_to(product_categories_url)
    end
  end

end
